# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-10-19 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0015_auto_20181011_0422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='theme',
            field=models.CharField(choices=[('earth', 'Earth'), ('grass', 'Grass'), ('lemon', 'Lemon'), ('odoo', 'Odoo'), ('openbravo', 'Openbravo'), ('orange', 'Orange'), ('snow', 'Snow'), ('strawberry', 'Strawberry'), ('water', 'Water'), ('laura', 'Laura')], default='laura', max_length=20, verbose_name='theme'),
        ),
    ]
