# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-10-22 18:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0016_auto_20181019_1410'),
        ('common', '0016_auto_20181019_1607'),
    ]

    operations = [
    ]
