# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-30 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0017_merge_20181022_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='operation',
            field=models.TextField(blank=True, choices=[('operation_forecast_ok', 'operation forecast ok'), ('operation_forecast_nok', 'operation forecast nok'), ('operation_forecast_cancel', 'operation forecast cancel'), ('operation_forecast_release', 'operation forecast release')], null=True, verbose_name='comment operation'),
        ),
    ]
