# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-10-31 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0018_comment_operation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='operation',
            field=models.TextField(blank=True, choices=[('operation_forecast_ok', 'operation_forecast_ok'), ('operation_forecast_nok', 'operation_forecast_nok'), ('operation_forecast_cancel', 'operation_forecast_cancel'), ('operation_forecast_release', 'operation_forecast_release')], null=True, verbose_name='comment operation'),
        ),
    ]
