# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-11-09 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0019_auto_20181031_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='theme',
            field=models.CharField(choices=[('laura', 'Laura'), ('earth', 'Earth'), ('grass', 'Grass'), ('lemon', 'Lemon'), ('odoo', 'Odoo'), ('openbravo', 'Openbravo'), ('orange', 'Orange'), ('snow', 'Snow'), ('strawberry', 'Strawberry'), ('water', 'Water')], default='laura', max_length=20, verbose_name='theme'),
        ),
    ]
