# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-01-24 10:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0021_datastaginglog'),
        ('common', '0021_parameter_value_type'),
    ]

    operations = [
    ]
