# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-08 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execute', '0003_Task_name_size_up'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='logfile',
            field=models.TextField(editable=False, max_length=200, null=True, verbose_name='log file'),
        ),
    ]
