# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-01-23 17:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('execute', '0005_datastaginglog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datastaginglog',
            old_name='create_user_nr',
            new_name='create_user_name',
        ),
        migrations.AddField(
            model_name='datastaginglog',
            name='task',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='execute.Task', verbose_name='task'),
        ),
        migrations.AddField(
            model_name='datastaginglog',
            name='user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='task',
            name='create_user_name',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=100, null=True, verbose_name='create_user_nr'),
        ),
    ]
