# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-11-01 16:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecast',
            name='parsed_date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='parsed_date'),
        ),
        migrations.AddField(
            model_name='forecastyear',
            name='parsed_date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='parsed_date'),
        ),
    ]
