# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-30 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecast',
            name='status',
            field=models.CharField(choices=[('init', 'init'), ('ok', 'ok'), ('nok', 'nok'), ('cancel', 'cancel'), ('release', 'release'), ('confirm', 'confirm')], default='init', max_length=20, verbose_name='status'),
        ),
        migrations.AlterUniqueTogether(
            name='forecast',
            unique_together=set([('item', 'location', 'customer', 'date_number', 'version')]),
        ),
    ]
