# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-11 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.AutoField(help_text='Unique identifier', primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='location',
            name='nr',
            field=models.CharField(db_index=True, max_length=300, unique=True, verbose_name='nr'),
        ),
    ]
