# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-26 15:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0002_auto_20181025_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('source', models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='source')),
                ('lastmodified', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='last modified')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='updated_at')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
            ],
            options={
                'verbose_name': 'forecast',
                'verbose_name_plural': 'forecasts',
                'db_table': 'forecast',
                'ordering': ['id'],
                'abstract': False,
            },
        ),
    ]
