# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-11-02 04:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0003_change_forecast_unique_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecast',
            name='ratio',
            field=models.DecimalField(blank=True, decimal_places=8, default=100, max_digits=20, verbose_name='forecast ratio'),
        ),
        migrations.AlterField(
            model_name='forecastyear',
            name='ratio',
            field=models.DecimalField(blank=True, decimal_places=8, default=100, max_digits=20, verbose_name='forecast ratio'),
        ),
    ]
