# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-11-05 04:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0004_change_forecast_ratio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='defaultvalue',
            field=models.DecimalField(blank=True, decimal_places=8, default=0.0, help_text='Value to be used when no entry is effective', max_digits=20, null=True, verbose_name='default value'),
        ),
        migrations.AlterField(
            model_name='calendarbucket',
            name='priority',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='priority'),
        ),
        migrations.AlterField(
            model_name='calendarbucket',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=8, default=0.0, max_digits=20, verbose_name='value'),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='new_product_plan_qty',
            field=models.DecimalField(blank=True, decimal_places=8, default=0, max_digits=20, verbose_name='new product plan qty'),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='normal_qty',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20, verbose_name='normal qty'),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='promotion_qty',
            field=models.DecimalField(blank=True, decimal_places=8, default=0, max_digits=20, verbose_name='promotion qty'),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='year',
            field=models.IntegerField(db_index=True, verbose_name='year'),
        ),
        migrations.AlterField(
            model_name='forecastyear',
            name='new_product_plan_qty',
            field=models.DecimalField(blank=True, decimal_places=8, default=0, max_digits=20, verbose_name='new product plan qty'),
        ),
        migrations.AlterField(
            model_name='forecastyear',
            name='normal_qty',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20, verbose_name='normal qty'),
        ),
        migrations.AlterField(
            model_name='forecastyear',
            name='promotion_qty',
            field=models.DecimalField(blank=True, decimal_places=8, default=0, max_digits=20, verbose_name='promotion qty'),
        ),
        migrations.AlterField(
            model_name='itemdistribution',
            name='load_time',
            field=models.DecimalField(blank=True, decimal_places=8, default=0.0, max_digits=20, null=True, verbose_name='load time'),
        ),
        migrations.AlterField(
            model_name='itemdistribution',
            name='receive_time',
            field=models.DecimalField(blank=True, decimal_places=8, default=0.0, max_digits=20, null=True, verbose_name='receive time'),
        ),
        migrations.AlterField(
            model_name='itemdistribution',
            name='resource_qty',
            field=models.DecimalField(blank=True, decimal_places=8, default=1.0, help_text='Resource capacity consumed per distributed unit', max_digits=20, null=True, verbose_name='resource quantity'),
        ),
        migrations.AlterField(
            model_name='itemdistribution',
            name='size_minimum',
            field=models.DecimalField(blank=True, decimal_places=8, default=1.0, max_digits=20, null=True, verbose_name='size minimum'),
        ),
        migrations.AlterField(
            model_name='itemdistribution',
            name='size_multiple',
            field=models.DecimalField(blank=True, decimal_places=8, default=0.0, max_digits=20, null=True, verbose_name='size multiple'),
        ),
        migrations.AlterField(
            model_name='itemdistribution',
            name='transit_time',
            field=models.DecimalField(blank=True, decimal_places=8, default=0.0, max_digits=20, null=True, verbose_name='transit time'),
        ),
        migrations.AlterField(
            model_name='itemsuccessor',
            name='priority',
            field=models.IntegerField(default=0, verbose_name='priority'),
        ),
        migrations.AlterField(
            model_name='itemsuccessor',
            name='ratio',
            field=models.DecimalField(decimal_places=8, default=100.0, max_digits=20, verbose_name='ratio'),
        ),
        migrations.AlterField(
            model_name='itemsupplier',
            name='load_time',
            field=models.DecimalField(blank=True, decimal_places=8, default=0.0, max_digits=20, null=True, verbose_name='load time'),
        ),
        migrations.AlterField(
            model_name='itemsupplier',
            name='priority',
            field=models.IntegerField(default=0, help_text='Priority among all alternates', verbose_name='priority'),
        ),
        migrations.AlterField(
            model_name='itemsupplier',
            name='product_time',
            field=models.DecimalField(blank=True, decimal_places=8, default=0.0, max_digits=20, null=True, verbose_name='product time'),
        ),
        migrations.AlterField(
            model_name='itemsupplier',
            name='ratio',
            field=models.DecimalField(blank=True, decimal_places=8, default=100, max_digits=20, null=True, verbose_name='ratio'),
        ),
        migrations.AlterField(
            model_name='itemsupplier',
            name='receive_time',
            field=models.DecimalField(blank=True, decimal_places=8, default=0.0, max_digits=20, null=True, verbose_name='receive time'),
        ),
        migrations.AlterField(
            model_name='itemsupplier',
            name='transit_time',
            field=models.DecimalField(blank=True, decimal_places=8, default=0.0, max_digits=20, null=True, verbose_name='transit time'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='min_num_per',
            field=models.DecimalField(blank=True, decimal_places=8, default=1.0, help_text='A minimum quantity for operationplans', max_digits=20, null=True, verbose_name='min num per'),
        ),
        migrations.AlterField(
            model_name='operationmaterial',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=8, default=1.0, help_text='Quantity to consume or produce per operationplan unit', max_digits=20, null=True, verbose_name='quantity'),
        ),
        migrations.AlterField(
            model_name='operationplan',
            name='color',
            field=models.DecimalField(blank=True, decimal_places=8, default=0.0, max_digits=20, null=True, verbose_name='color'),
        ),
        migrations.AlterField(
            model_name='operationplan',
            name='quantity',
            field=models.DecimalField(decimal_places=8, default=1.0, max_digits=20, verbose_name='quantity'),
        ),
        migrations.AlterField(
            model_name='operationresource',
            name='quantity',
            field=models.DecimalField(decimal_places=8, default=1.0, max_digits=20, verbose_name='quantity'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='efficiency',
            field=models.DecimalField(blank=True, decimal_places=8, default=100.0, help_text='Efficiency percentage of the resource', max_digits=20, null=True, verbose_name='efficiency'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='efficiency_calendar',
            field=models.ForeignKey(blank=True, help_text='Calendar defining the efficiency percentage of the resource varying over time', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resource_efficiency_calendar', to='input.Calendar', verbose_name='efficiency calendar'),
        ),
        migrations.AlterField(
            model_name='setuprule',
            name='priority',
            field=models.IntegerField(default=0, verbose_name='priority'),
        ),
    ]
