# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-11-07 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0005_change_fields_default_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='lock_expire_at',
            field=models.DateField(blank=True, null=True, verbose_name='lock expire at'),
        ),
        migrations.AddField(
            model_name='item',
            name='lock_type',
            field=models.CharField(blank=True, choices=[('locked', 'locked'), ('unlocked', 'unlocked')], max_length=20, null=True, verbose_name='lock type'),
        ),
        migrations.AddField(
            model_name='item',
            name='plan_strategy',
            field=models.CharField(blank=True, choices=[('MTS', 'MTS'), ('MTO', 'MTO'), ('ETO', 'ETO')], max_length=20, null=True, verbose_name='plan strategy'),
        ),
        migrations.AddField(
            model_name='item',
            name='price_abc',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=20, null=True, verbose_name='price abc'),
        ),
        migrations.AddField(
            model_name='item',
            name='qty_abc',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=20, null=True, verbose_name='qty abc'),
        ),
        migrations.AddField(
            model_name='itemcustomer',
            name='lock_type',
            field=models.CharField(blank=True, choices=[('locked', 'locked'), ('unlocked', 'unlocked')], max_length=20, null=True, verbose_name='lock type'),
        ),
        migrations.AddField(
            model_name='itemsupplier',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='descriptiony'),
        ),
        migrations.AddField(
            model_name='itemsupplier',
            name='order_max_qty',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20, verbose_name='order max qty'),
        ),
        migrations.AddField(
            model_name='itemsupplier',
            name='order_unit_qty',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20, verbose_name='order unit qty'),
        ),
        migrations.AddField(
            model_name='itemsupplier',
            name='plan_load_date',
            field=models.DateField(blank=True, null=True, verbose_name='plan load date'),
        ),
        migrations.AddField(
            model_name='itemsupplier',
            name='plan_receive_date',
            field=models.DateField(blank=True, null=True, verbose_name='plan receive date'),
        ),
        migrations.AddField(
            model_name='itemsupplier',
            name='plan_supplier_date',
            field=models.DateField(blank=True, null=True, verbose_name='plan supplier date'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='city',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='city'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='contact',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='contact'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='country',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='country'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='phone'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='telephone',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='telephone'),
        ),
        migrations.AlterField(
            model_name='itemsupplier',
            name='origin_country',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='origin country'),
        ),
    ]
