# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-11-07 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0006_auto_20181107_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcustomer',
            name='lock_expire_at',
            field=models.DateField(blank=True, null=True, verbose_name='lock expire at'),
        ),
    ]
