# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-11-08 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0007_itemcustomer_lock_expire_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='email',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='email'),
        ),
    ]
