# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-11-08 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0008_supplier_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsupplier',
            name='pallet_volume',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='pallet volume'),
        ),
    ]
