# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-11-08 14:33
from __future__ import unicode_literals

from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0009_alter_item_supplier_pallet_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemsupplier',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,blank=False,null=False, related_name='itemsupplier_location', to='input.Location', verbose_name='location'),
        ),
    ]
