# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-11-15 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0010_add_location_to_itemsupplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecast',
            name='date_type',
            field=models.CharField(choices=[('W', 'W'), ('M', 'M')], default='W', max_length=20, verbose_name='date_type'),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='new_product_plan_qty',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20, verbose_name='new product plan qty'),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='promotion_qty',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20, verbose_name='promotion qty'),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='ratio',
            field=models.DecimalField(decimal_places=8, default=100, max_digits=20, verbose_name='forecast ratio'),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(blank=True, choices=[('S0', 'S0'), ('S1', 'S1'), ('S2', 'S2'), ('S3', 'S3'), ('S4', 'S4')], max_length=20, null=True, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='itemcustomer',
            name='status',
            field=models.CharField(blank=True, choices=[('S0', 'S0'), ('S1', 'S1'), ('S2', 'S2'), ('S3', 'S3'), ('S4', 'S4')], max_length=20, null=True, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='itemsupplier',
            name='status',
            field=models.CharField(choices=[('A0', 'A0'), ('A1', 'A1'), ('A2', 'A2'), ('A3', 'A3')], max_length=20, verbose_name='status'),
        ),
    ]
