# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-11-15 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0012_auto_20181115_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(blank=False, choices=[('FG', 'FG'), ('WIP', 'WIP'), ('RM', 'RM')], max_length=20, null=False, verbose_name='type'),
        ),
    ]
