# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-01-21 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0014_create_itemlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemsuccessor',
            name='relation_type',
            field=models.CharField(blank=True, choices=[('successor', 'successor'), ('replacement', 'replacement')], max_length=20, null=True, verbose_name='relation type'),
        ),
        migrations.AlterUniqueTogether(
            name='itemlocation',
            unique_together=set([('item', 'location')]),
        ),
    ]
