# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-01-21 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0015_add_relation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsuccessor',
            name='relation_type',
            field=models.CharField(choices=[('successor', 'successor'), ('replacement', 'replacement')], max_length=20, verbose_name='relation type'),
        ),
    ]
