# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-01-22 17:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0016_alter_relation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecast',
            name='priority',
            field=models.IntegerField(default=0, help_text='Priority of the demand (lower numbers indicate more important demands)', verbose_name='priority'),
        ),
        migrations.AlterField(
            model_name='itemlocation',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemlocation_item', to='input.Item', verbose_name='item'),
        ),
    ]
