# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-01-22 17:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0017_add_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryParameter',
            fields=[
                ('source', models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='source')),
                ('lastmodified', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='last modified')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='updated_at')),
                ('id', models.AutoField(help_text='Unique identifier', primary_key=True, serialize=False, verbose_name='id')),
                ('rop_cover_period', models.IntegerField(verbose_name='rop cover period')),
                ('safetystock_cover_period', models.IntegerField(verbose_name='safetystock cover period')),
                ('safetysotck_min_qty', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='safety sotck min qty')),
                ('safetysotck_max_qty', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='safety sotck max qty')),
                ('safetystock_qty_by_system', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='system safety stock')),
                ('service_level', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='service level')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventoryparameter_item', to='input.Item', verbose_name='item')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventoryparameter_location', to='input.Location', verbose_name='location')),
            ],
            options={
                'verbose_name': 'inventory parameter',
                'verbose_name_plural': 'inventory parameters',
                'db_table': 'inventoryparameter',
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='inventoryparameter',
            unique_together=set([('item', 'location')]),
        ),
    ]
