# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-01-22 18:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0019_salesorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrderItem',
            fields=[
                ('source', models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='source')),
                ('lastmodified', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='last modified')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='updated_at')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('line_no', models.CharField(blank=True, max_length=300, null=True, verbose_name='line no')),
                ('qty', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='qty')),
                ('schedule_qty', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='schedule qty')),
                ('deliver_qty', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='deliver qty')),
                ('due', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='due')),
                ('priority', models.IntegerField(blank=True, default=0, null=True, verbose_name='priority')),
                ('status', models.CharField(blank=True, choices=[('open', 'open'), ('close', 'close'), ('canceled', 'canceled'), ('invoiced', 'invoiced')], max_length=20, null=True, verbose_name='status')),
                ('max_lateness', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='max lateness')),
                ('min_shipment', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='min shipment')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salesorderitem_item', to='input.Item', verbose_name='item')),
                ('sales_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salesorderitem_saleorder', to='input.SalesOrder', verbose_name='sales order')),
            ],
            options={
                'verbose_name': 'sales order item',
                'verbose_name_plural': 'sales orders items',
                'db_table': 'sales_order_item',
                'ordering': ['id'],
                'abstract': False,
            },
        ),
    ]
