# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-01-23 10:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0020_salesorderitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeliveryOrder',
        ),
        migrations.CreateModel(
            name='DeliveryOrder',
            fields=[
                ('source', models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='source')),
                ('lastmodified', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='last modified')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='updated_at')),
                ('id', models.AutoField(help_text='Unique identifier', primary_key=True, serialize=False, verbose_name='id')),
                ('nr', models.CharField(blank=True, db_index=True, max_length=300, null=True, unique=True, verbose_name='nr')),
                ('type', models.CharField(blank=True, choices=[('outbound', 'outbound'), ('inbound', 'inbound'), ('other', 'other')], max_length=20, null=True, verbose_name='type')),
                ('status', models.CharField(blank=True, choices=[('open', 'open'), ('git', 'git'), ('partially_delivered', 'partially delivered'), ('fully_delivered', 'fully delivered'), ('rejected', 'rejected'), ('canceled', 'canceled')], max_length=20, null=True, verbose_name='status')),
                ('schedule_arrive_at', models.DateTimeField(blank=True, null=True, verbose_name='schedule arrive at')),
                ('start_ship_at', models.DateTimeField(blank=True, null=True, verbose_name='start ship at')),
                ('actual_arrive_at', models.DateTimeField(blank=True, null=True, verbose_name='actual arrive at')),
                ('delay', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='delay')),
                ('deliver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliveryorder_deliver', to='input.Customer', verbose_name='deliver')),
                ('deliver_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliveryorder_deliver_source', to='input.Forecast', verbose_name='deliver source')),
                ('destination_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliveryorder_destination_location', to='input.Location', verbose_name='destination location')),
                ('source_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliveryorder_source_location', to='input.Location', verbose_name='source location')),
            ],
            options={
                'verbose_name': 'delivery order',
                'verbose_name_plural': 'delivery orders',
                'db_table': 'deliveryorder',
                'ordering': ['id'],
                'abstract': False,
            },
        ),
    ]
