# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-01-23 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0021_create_deliveryorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryparameter',
            name='rop',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='rop'),
        ),
        migrations.AddField(
            model_name='inventoryparameter',
            name='roq_by_system',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='system rop'),
        ),
    ]
