# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-01-23 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0022_add_files_to_inventoreypara'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryparameter',
            name='rop',
            field=models.DecimalField(decimal_places=8, max_digits=20, verbose_name='rop'),
        ),
        migrations.AlterField(
            model_name='inventoryparameter',
            name='roq_by_system',
            field=models.DecimalField(decimal_places=8, max_digits=20, verbose_name='system rop'),
        ),
    ]
