# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-01-23 11:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0023_alter_fields_to_inventorypara'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryOrderItem',
            fields=[
                ('source', models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='source')),
                ('lastmodified', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='last modified')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='updated_at')),
                ('id', models.AutoField(help_text='Unique identifier', primary_key=True, serialize=False, verbose_name='id')),
                ('line_no', models.CharField(blank=True, max_length=300, null=True, verbose_name='line no')),
                ('deliver_qty', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='deliver qty')),
                ('status', models.CharField(blank=True, choices=[('open', 'open'), ('git', 'git'), ('partially_delivered', 'partially delivered'), ('fully_delivered', 'fully delivered'), ('rejected', 'rejected'), ('canceled', 'canceled')], max_length=20, null=True, verbose_name='status')),
                ('start_ship_at', models.DateTimeField(blank=True, null=True, verbose_name='start ship at')),
                ('actual_arrive_at', models.DateTimeField(blank=True, null=True, verbose_name='actual arrive at')),
                ('delay', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='delay')),
                ('deliver_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliveryorderitem_deliver_source', to='input.Forecast', verbose_name='deliver source')),
                ('delivery_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliveryorderitem_delivery_order', to='input.DeliveryOrder', verbose_name='destination order')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveryorderitem_item', to='input.Item', verbose_name='item')),
            ],
            options={
                'verbose_name': 'delivery order item',
                'verbose_name_plural': 'delivery order items',
                'db_table': 'delivery_order_item',
                'ordering': ['id'],
                'abstract': False,
            },
        ),
    ]
