# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-01-23 12:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0024_deliveryorderitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PurchaseOrder',
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('source', models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='source')),
                ('lastmodified', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='last modified')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='updated_at')),
                ('id', models.AutoField(help_text='Unique identifier', primary_key=True, serialize=False, verbose_name='id')),
                ('nr', models.CharField(blank=True, max_length=300, null=True, verbose_name='nr')),
                ('status', models.CharField(blank=True, choices=[('open', 'open'), ('git', 'git'), ('partially_delivered', 'partially delivered'), ('fully_delivered', 'fully delivered'), ('rejected', 'rejected'), ('canceled', 'canceled')], max_length=20, null=True, verbose_name='status')),
                ('order_at', models.DateTimeField(blank=True, null=True, verbose_name='order at')),
                ('start_ship_at', models.DateTimeField(blank=True, null=True, verbose_name='start ship at')),
                ('actual_arrive_at', models.DateTimeField(blank=True, null=True, verbose_name='actual arrive at')),
                ('delay', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='delay')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchaseorder_location', to='input.Location', verbose_name='location')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchaseorder_supplier', to='input.Supplier', verbose_name='supplier')),
            ],
            options={
                'verbose_name': 'purchase order',
                'verbose_name_plural': 'purchase orders',
                'db_table': 'purchase_order',
                'ordering': ['id'],
                'abstract': False,
            },
        ),
    ]
