# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-01-23 14:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0026_purchaseorderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('source', models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='source')),
                ('lastmodified', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='last modified')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='updated_at')),
                ('id', models.AutoField(help_text='Unique identifier', primary_key=True, serialize=False, verbose_name='id')),
                ('nr', models.CharField(blank=True, max_length=300, null=True, verbose_name='nr')),
                ('status', models.CharField(blank=True, choices=[('init', 'init'), ('open', 'open'), ('closed', 'closed'), ('canceled', 'canceled')], max_length=20, null=True, verbose_name='status')),
                ('schedule_start_at', models.DateTimeField(blank=True, null=True, verbose_name='schedule start at')),
                ('actual_start_at', models.DateTimeField(blank=True, null=True, verbose_name='actual arrive at')),
                ('schedule_end_at', models.DateTimeField(blank=True, null=True, verbose_name='schedule end at')),
                ('actual_end_at', models.DateTimeField(blank=True, null=True, verbose_name='actual end at')),
                ('delay', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='delay')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workorder_location', to='input.Location', verbose_name='location')),
            ],
            options={
                'verbose_name': 'work order',
                'verbose_name_plural': 'work orders',
                'db_table': 'work_order',
                'ordering': ['id'],
                'abstract': False,
            },
        ),
    ]
