# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-01-23 15:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0028_workorderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryparameter',
            old_name='roq_by_system',
            new_name='rop_by_system',
        ),
    ]
