# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-01-23 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0031_alter_deliveryorder_nr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='nr',
            field=models.CharField(db_index=True, max_length=300, unique=True, verbose_name='nr'),
        ),
    ]
