# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-01-23 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0032_alter_salesorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='nr',
            field=models.CharField(max_length=300, verbose_name='nr'),
        ),
    ]
