# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-01-24 10:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0034_rename_inventorypara'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryparameter',
            name='safetystock_max_qty',
            field=models.DecimalField(decimal_places=8, max_digits=20, verbose_name='safety stock max qty'),
        ),
        migrations.AlterField(
            model_name='inventoryparameter',
            name='safetystock_min_qty',
            field=models.DecimalField(decimal_places=8, max_digits=20, verbose_name='safety stock min qty'),
        ),
        migrations.AlterField(
            model_name='workorderitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workorderitem_item', to='input.Item', verbose_name='item'),
        ),
    ]
