# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-01-24 18:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0036_delete_field_operation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryorderitem',
            name='delivery_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliveryorderitem_delivery_order', to='input.DeliveryOrder', verbose_name='delivery order'),
        ),
    ]
