# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-01-24 18:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0038_delete_demand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('lastmodified', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='last modified')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='updated_at')),
                ('id', models.AutoField(help_text='Unique identifier', primary_key=True, serialize=False, verbose_name='id')),
                ('qty', models.DecimalField(blank=True, db_index=True, decimal_places=8, max_digits=20, null=True, verbose_name='qty')),
                ('schedule_qty', models.DecimalField(blank=True, db_index=True, decimal_places=8, max_digits=20, null=True, verbose_name='schedule qty')),
                ('deliver_qty', models.DecimalField(blank=True, db_index=True, decimal_places=8, max_digits=20, null=True, verbose_name='deliver qty')),
                ('due', models.DateTimeField(blank=True, null=True, verbose_name='due')),
                ('priority', models.IntegerField(blank=True, default=0, null=True, verbose_name='priority')),
                ('status', models.CharField(blank=True, choices=[('init', 'init'), ('open', 'open'), ('release', 'release'), ('closed', 'closed'), ('canceled', 'canceled')], max_length=20, null=True, verbose_name='status')),
                ('max_lateness', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='max lateness')),
                ('min_shipment', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='min shipment')),
                ('closed_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='closed at')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='demand_customer', to='input.Customer', verbose_name='customer')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demand_item', to='input.Item', verbose_name='item')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demand_location', to='input.Location', verbose_name='location')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demand_source', to='input.Forecast', verbose_name='source')),
            ],
            options={
                'verbose_name': 'demand',
                'verbose_name_plural': 'demands',
                'db_table': 'demand',
                'ordering': ['id'],
                'abstract': False,
            },
        ),
    ]
