# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-01-25 15:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0040_create_demandrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemBom',
            fields=[
                ('source', models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='source')),
                ('lastmodified', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='last modified')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='updated_at')),
                ('id', models.AutoField(help_text='Unique identifier', primary_key=True, serialize=False, verbose_name='id')),
                ('nr', models.CharField(db_index=True, max_length=300, unique=True, verbose_name='nr')),
                ('qty', models.IntegerField(verbose_name='qty')),
                ('effective_start', models.DateField(blank=True, null=True, verbose_name='effective start')),
                ('effective_end', models.DateField(blank=True, null=True, verbose_name='effective end')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itembom_item', to='input.Item', verbose_name='item')),
                ('item_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itembom_item_location', to='input.ItemLocation', verbose_name='item location')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itembom_parent', to='input.Item', verbose_name='owner')),
            ],
            options={
                'verbose_name': 'item bom',
                'verbose_name_plural': 'item boms',
                'db_table': 'item_bom',
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='forecast',
            name='status',
            field=models.CharField(choices=[('init', 'forecast init'), ('ok', 'forecast ok'), ('nok', 'forecast nok'), ('cancel', 'forecast cancel'), ('release', 'forecast release'), ('confirm', 'forecast confirm'), ('CAN_CALCULATE_MDS_STATUS', ('confirm',))], default='init', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='forecastversion',
            name='status',
            field=models.CharField(choices=[('init', 'forecast init'), ('ok', 'forecast ok'), ('nok', 'forecast nok'), ('cancel', 'forecast cancel'), ('release', 'forecast release'), ('confirm', 'forecast confirm'), ('CAN_CALCULATE_MDS_STATUS', ('confirm',))], default='init', max_length=20, verbose_name='status'),
        ),
        migrations.AlterUniqueTogether(
            name='itembom',
            unique_together=set([('item', 'parent')]),
        ),
    ]
