# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-01-25 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0042_create_itemrop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='status'),
        ),
    ]
