# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-01-28 14:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0044_alter_item_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forecastversion',
            options={'verbose_name': 'forecast version', 'verbose_name_plural': 'forecast versions'},
        ),
        migrations.AddField(
            model_name='itemropqty',
            name='date_type',
            field=models.CharField(blank=True, choices=[('W', 'W'), ('M', 'M')], default='W', max_length=20, null=True, verbose_name='date_type'),
        ),
        migrations.AddField(
            model_name='itemropqty',
            name='parsed_date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='parsed_date'),
        ),
        migrations.AddField(
            model_name='itemsafetystock',
            name='date_type',
            field=models.CharField(blank=True, choices=[('W', 'W'), ('M', 'M')], default='W', max_length=20, null=True, verbose_name='date_type'),
        ),
        migrations.AddField(
            model_name='itemsafetystock',
            name='parsed_date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='parsed_date'),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='status',
            field=models.CharField(choices=[('init', 'forecast init'), ('ok', 'forecast ok'), ('nok', 'forecast nok'), ('cancel', 'forecast cancel'), ('release', 'forecast release'), ('confirm', 'forecast confirm')], default='init', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='forecastversion',
            name='status',
            field=models.CharField(choices=[('init', 'forecast init'), ('ok', 'forecast ok'), ('nok', 'forecast nok'), ('cancel', 'forecast cancel'), ('release', 'forecast release'), ('confirm', 'forecast confirm')], default='init', max_length=20, verbose_name='status'),
        ),
    ]
